function init(self)
	go.animate(".", "position.y", go.PLAYBACK_LOOP_PINGPONG, 550, go.EASING_LINEAR, 1.5)
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	local getpos = go.get_position()

	daabbcc.updateRect("world",1,getpos.x, getpos.y,1300, 50 )
 
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
