

local enemy_group
local enemy_go
local enemy_go2
local enemy_id1
local enemy_id2

function init(self)
    enemy_group = aabb.new_group()
    enemy_go = msg.url("/go")
    enemy_go2 = msg.url("/go1")

    enemy_id1 = aabb.insert_gameobject(enemy_group, enemy_go, 80, 80,true)
   enemy_id2 = aabb.insert_gameobject(enemy_group, enemy_go2, 80, 80,true)

    go.animate(enemy_go, "position.x", go.PLAYBACK_LOOP_PINGPONG, 450,
               go.EASING_INOUTBOUNCE, 1)

  
end

function update(self, dt)

    local result = aabb.query_id(enemy_group, enemy_id1)
    pprint(result)
end
