[daabbcc]
title = DAABBCC
group = Runtime
help = Settings for DAABBCC extension

max_group_count.type = integer
max_group_count.default = 3

max_gameobject_count.type = integer
max_gameobject_count.default = 128

max_query_result_count.type = integer
max_query_result_count.default = 32

validate_gameobjects.type = bool
validate_gameobjects.label = Validate Gameobjects
